# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# OpenSPG server image with the Nebula (trsgraph) graph-store driver.
#
# Build the fat jar first:
#   dev/release/scripts/build-openspg-server-nebula.sh
#
# Then build this image from dev/release:
#   docker compose -f docker-compose.local.yml build server

ARG OPENSPG_BASE_IMAGE=spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-server:latest
FROM ${OPENSPG_BASE_IMAGE}

COPY nebula-runtime/arks-sofaboot-0.0.1-SNAPSHOT-executable.jar /arks-sofaboot-0.0.1-SNAPSHOT-executable.jar

EXPOSE 8887
